---
# tasks file for ansible_role_regenerate_fingerprint
- name: Ensure absence of old freeze files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ecdsa_key.pub
    - /etc/ssh/ssh_host_ed25519_key
    - /etc/ssh/ssh_host_ed25519_key.pub
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_rsa_key.pub
  when: ansible_facts['os_family'] == "RedHat"
- name: Generate an OpenSSH keypair with the default values (448 bits, ed25519) and encrypted private key
  community.crypto.openssh_keypair:
    path: /etc/ssh/ssh_host_ed25519_key
    type: ed25519
    owner: root
    group: ssh_keys
    mode: '0640'
    force: true
  when: ansible_facts['os_family'] == "RedHat"
  notify: "Restart ssh service"
- name: Generate an OpenSSH keypair with the default values (384 bits, ecdsa) and encrypted private key
  community.crypto.openssh_keypair:
    path: /etc/ssh/ssh_host_ecdsa_key
    type: ecdsa
    owner: root
    group: ssh_keys
    mode: '0640'
    force: true
  when: ansible_facts['os_family'] == "RedHat"
  notify: "Restart ssh service"
- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa) and encrypted private key
  community.crypto.openssh_keypair:
    path: /etc/ssh/ssh_host_rsa_key
    type: rsa
    owner: root
    group: ssh_keys
    mode: '0640'
    force: true
  when: ansible_facts['os_family'] == "RedHat"
  notify: "Restart ssh service"
- name: Ensure good chmod of pub files
  ansible.builtin.file:
    path: '{{ item }}'
    state: file
    owner: root
    group: root
    mode: '0644'
  with_items:
    - /etc/ssh/ssh_host_ecdsa_key.pub
    - /etc/ssh/ssh_host_ed25519_key.pub
    - /etc/ssh/ssh_host_rsa_key.pub
  when: ansible_facts['os_family'] == "RedHat"
